
import { Toaster } from "react-hot-toast";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Header from "./components/Ui/Header";
import { CartProvider } from "./context/CartContext";
import { ProductsProvider } from "./context/FilterResultContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Astrape",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <CartProvider>
        <ProductsProvider>
        <Toaster position="top-right" toastOptions={{ duration: 1500 }}/>

        <Header/>
        {children}
        </ProductsProvider>
        </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
